---
name: my_pyramid
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/backgrounds/
  - assets/backgrounds/components/
  - assets/cards/
  - assets/home/
  - assets/home/components/
  - assets/splashScreens/
  - assets/video/
